---
title: "Calendar steps"
author: "Tanguy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentation

### Notation

Dans la suite :
- $i$ désigne le jour de la semaine
- $j$ ou $mois_j$ désigne le numéro du mois de l'année

### Préparation du calendrier

- On compte les jours ($NbDays$ est le nombre total de jour du mois) :
$Day_i$ est le nombre de jour n°i dans le mois ($Day_1$ est le dimanche, $Day_2$ le lundi, ... $Day_7$ est le samedi)

- On compte les jours fériés 
$Off_i$ est le nombre de jour férié tombant un jour n°i dans le mois ($Off_1$ pour tous les dimanches, $Off_2$ les lundis, ... et $Off_7$ les samedis)

- On distingue alors jours IN et jours OFF (selon fériés et vacances). En France la liste des jours off est :
    * 1er de l'an (1er janvier)
    * Lundi de Paques
    * Jeudi de l'ascension
    * Lundi de pentecôte
    * Fête du travail (1er mai)
    * Armistice de 1945 (8 mai) mais uniquement depuis 1982
    * Fête nationale (14 juillet)
    * L'assomption (15 Août)
    * Toussaint (1 novembre)
    * Armistice de 1918 (11 novembre)
    * Noël (25 décembre)
    * les différents ponts (les lundi et vendredi à chaque fois qu'il y a un mardi ou un jeudi de férié) 

Ainsi on peut définir les jours ouvrables :
$In_i = Day_i - Off_i$ pour $i$ entre 1 et 7.

- On créé les jours TD (tradings days) comme contrast par rapport à un référence (généralement le dimanche) :
$TD_i = Day_i - Day_1$ pour $i$ entre 2 et 7. 
Par abus de notation, des fois i parcourt [1, 6] et non [2, 7] et alors 1 désigne le lundi et 6 le samedi.

- On créé la variable WD (working days) qui calcule un nombre moyen de jours travaillé (en contraste)
$$ WD = \left(\sum_{i = 2}^{6} Day_i\right) - \frac{5}{2} \times \left(Day_1 + Day_7\right) $$
On applique la formule plus générale :

$$ reg_i = group_i - group_0 \times \frac{\# group_i}{\# group_0} $$ avec ici $i = 1$ et $group_1 = {2, 3, 4, 5, 6}$ et $group_0 = {1, 7}$

- On créé les "Working week-days" = jours ouvrables (TD), en opposition les "Publics Holydays" (PH) et les "Weekday contrast" (Weekdays) :
$$ TD = \sum_{i = 2}^{6} In_i $$
$$ PH = \sum_{i = 2}^{6} Off_i $$
$$ Weekdays = TD - \frac{5}{2} \times \left(PH + Day_1 + Day_7\right) $$

### Retrait des moyennes de long-terme

- On va calculer les moyennes de long-terme pour les variables $Day_i$ et les $Off_i$. Ces moyennes se calculent mois par mois :
$mean\_Day_{i, mois\_j} = \sum_{annees} Day_{i, mois\_j}$ avec $i$ l'indice du jour de la semaine entre 1 et 7 et $mois\_j$ le numéro du mois entre 1 et 12.
$mean\_Off_{i, mois\_j} = \sum_{annees} Off_{i, mois\_j}$ avec $i$ l'indice du jour de la semaine entre 1 et 7 et $mois\_j$ le numéro du mois entre 1 et 12

- On peut ensuite recalculer de nouvelles variables :
$$ Day_i\_corr = Day_i - mean\_Day_i $$, 
$$ Off_i\_corr = Off_i - mean\_Off_i $$, 
$$ In_i\_corr = Day_i\_corr - Off_i\_corr $$, 
Ainsi que toutes les autres variables présentées précédemment avec les nouveaux $Day_i\_corr$, $Off_i\_corr$ et $In_i\_corr$.

### Calcul des variables de regresseurs à partir des groupes

Pour créer un jeu de régresseurs, nous regroupons les jours de certains types entre eux. Par exemple :
- le jeu REG1 créé 2 groupes de jours 
    * $G_1$ = jours ouvrables
    * $G_0$ = les autres
- le jeu REG6 créé 7 groupes de jours 
    * $G_1$ = lundi ouvrables
    * $G_2$ = mardi ouvrables
    * $G_3$ = mercredi ouvrables
    * $G_4$ = jeudi ouvrables
    * $G_5$ = vendredi ouvrables
    * $G_6$ = samedi ouvrables
    * $G_0$ = les autres)
- et d'autres (REG5, REG3, ...)

Nous allons ensuite créer les regresseurs de calendrier comme variable de contraste par rapport à une référence. On prend généralement le groupe 0 comme groupe de référence.

Afin d'introduire de la comparabilité entre les groupes et avoir de l'homogénéité dans nos contrastes, nous allons pondérer le groupe 0 à la hauteur de la répartition du nombre de jour entre le groupe i et le groupe 0.

Nos régresseurs s'écrivent ainsi :

$$ REG_n\_AC_i = REG_i - \omega_i REG_0 $$ avec ici $n$ qui vaut 1, 3, 5, 6, ... et $i$ entre 1 et $n$.

De manière générale, les $\omega_i$ sont calculés à partir de la taille des groupes :
$$ \omega_i = \frac{\# group_i}{\# group_0} $$

- Pour les jeux de régresseurs issus de JD+ (*package rjd3modelling*), les $\omega_i$ sont calculés entre les jours "In". Ainsi dans une semaine "classique", il y a 5 jours ouvrables (du lundi au vendredi) et 2 jours de week-end (samedi et dimanche).
    * pour REG6, $\omega_i = 1$ car chaque groupe $G_i$ ne contient qu'un jour
    * pour REG1, $\omega_i = \frac{5}{2}$ car le groupe 1 $G_1$ (jours ouvrables) contient les jours du lundi au vendredi et le groupe 0 $G_0$ contient le samedi et le dimanche.
    * ... selon les configurations des groupes

- Pour les jeux de régresseurs issus des programmes SAS, les jours comptabilisés dans les pondérations sont les jours "In" et les jours "Off". 
    * pour REG6, $\omega_i = \frac{1}{8}$ car chaque groupe $G_i$ (pour $i\neq 0$) ne contient qu'un seul jour alors que le groupe 0 $G_0$ contient 8 jours dans le sens : 1 dimanche en semaine classique ("In") et 7 jours en semaine férié / vacances ("Off")
    * pour REG1, $\omega_i = \frac{5}{9}$ car le groupe 1 (jours ouvrables) contient 5 jours : les jours "In" du lundi au vendredi et le groupe 0 $G_0$ contient le samedi et le dimanche en semaine classique ("In") et 7 jours en semaine férié / vacances ("Off").
    * ... selon les configurations des groupes

Les espaces formés par la combinaison de chaque jeu de régressurs (RJD ou SAS) sont les mêmes. Mais les coefficients seront différents et interprétés différemment.

Enfin on peut formuler une remarque sur l'ordre des opérations. 

L'opération de calcul des moyennes prend une série (mensuelle ou trimestrielle) et retire sa moyenne par période :
$$ \overline{X} = I_1 \times (X - X_mean_1) + I_2 \times (X - X_mean_2) + ... + I_n \times (X - X_mean_n) $$ avec $I_i$ l'indicatrice de la période $i$ et $n$ le nombre total de période.

L'opération de contraste prend 2 séries et en fait une somme pondérée :
$$ X_contraste = X + \omega Y $$

Ces deux opérations sont des opérateurs linéaires ainsi on peut alterner ces 2 formules lors du calcul des constrastes :
$$ \overline{X + \omega Y} = \overline{X} + \omega \overline{Y} $$
